### PR TITLE
Added support for color palette

### PR DESCRIPTION
**Pull request by marvinrabe**
Some pickers accept a custom color palette. I can now add my palette like so:

```
Color::make('Field')->compact()->palette(['#beaf00', '#000', '#fff']);
```

### CODE REVIEW

**Comment by timothyasp** [comment]
Looks great - thanks for the pull.

**Comment by ArmeniaH** [comment]
<3

**Comment by milewski** [comment]
@timothyasp did you push this to packagist?

**Comment by skoyah** [comment]
> @timothyasp did you push this to packagist?

Maybe he forgot to tag it as a new minor version.

I changed my `composer.json` to expect "dev-master" and then ran a `composer update`

**Comment by marvinrabe** [comment]
@timothyasp Could you tag a release please?

**Comment by cgarofalo** [comment]
I have updated to "dev-master" and this does not work for me. It still displays the default palette.
Am I missing something obvious? @marvinrabe or @timothyasp Thanks!
My code:
```
Color::make( 'Color' )->compact()
			     ->palette( [
				     '#fff100',
				     '#ff8c00',
				     '#e81123',
				     '#ec008c',
				     '#68217a',
				     '#00188f',
				     '#00bcf2',
				     '#00b294',
				     '#009e49',
				     '#bad80a'
			     ] )
			     ->rules( 'required' ),
```

**Comment by marvinrabe** [comment]
@cgarofalo Can not see a reason why this should not work (based on your PHP code snippet). Maybe its has something to do with caching? Try to clear your browser cache. I am not sure if Nova caches package assets aswell. But it seems like your Browser uses the wrong JavaScript code.

**Comment by timothyasp** [comment]
I blew it and completely missed the tag on this.  Pushed to packagist, v1.0.3 and added some documentation and credit to you @marvinrabe 

Thanks for the pull again.

**Comment by cgarofalo** [comment]
@marvinrabe Yup it was the cache. >.>

**Pull request merged**
